on: [pull_request]

jobs:
  linter:
    runs-on: ubuntu-latest
    name: Lint flutter code
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Check json files
      uses: ValentinVignal/action-json-keys@v0.0
      with:
        matcher: 'json/**/*.json'